### PR TITLE
Add safe use of AAD to Safe Extensions framework

### PR DESCRIPTION
**Pull request by rohanmahy**
Incorporate AAD in the safe extensions framework to make a safe muxing of potentially multiple sources of authenticated_data

### CODE REVIEW

**Comment by kkohbrok** [comment]
It's been a while since we discussed this. @rohanmahy did you want to add a brief discussion noting that in contrast to other safe extension framework features, the use of the AAD is a little different, because the application can typically also just use the AAD? I know we discussed this but I can't remember what we decided on.

**Comment by rohanmahy** [comment]
Hi, if two extensions (safe or not) want to add AAD, there needs to be a way to mux and demux that data. I'm open to suggestions about what additional text you'd like added.

**Comment by kkohbrok** [comment]
I guess my question is how the implementation would know when to expect a SafeAAD item in the `authenticated_data` field. We probably need a rule that says something like: "If there is an extension (probably a group context extension) that sometimes makes use of the AAD field, then there MUST always be a SafeAAD item in `authenticated_data`, even if it's empty. Does that make sense? Otherwise the implementation won't know if it's parsing for a SafeAAD item or the application's (unsafe) AAD.

**Comment by rohanmahy** [comment]
> I guess my question is how the implementation would know when to expect a SafeAAD item in the `authenticated_data` field. We probably need a rule that says something like: "If there is an extension (probably a group context extension) that sometimes makes use of the AAD field, then there MUST always be a SafeAAD item in `authenticated_data`, even if it's empty. Does that make sense? Otherwise the implementation won't know if it's parsing for a SafeAAD item or the application's (unsafe) AAD.

I think there needs to be a SafeAAD GC extension. If it exists in a group, the first octet(s) of the AAD is/are the length of the SafeAAD vector (which could be zero). If there is any AAD left after that, it is non-Safe AAD.

Is that concept OK?

**Comment by kkohbrok** [comment]
That sounds good. Could you add/clarify that in the PR?

**Review by kkohbrok — APPROVED** [review]
Thanks, looks good to me!

**Comment by raphaelrobert** [comment]
Let's get this in. @rohanmahy can you please resolve the conflict?

**Pull request merged**
